language: bash

os:
  - linux

services:
  - docker
env:
  global:
    - TEST_FOO=1

before_install: # update to 17.09 to get COPY --from (multistage builds) and COPY --chown
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - jq --version
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) edge"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

script:
  - make test

after_success:
  - docker login -u="${DOCKER_USERNAME:?}" -p="${DOCKER_PASSWORD:?}";
  - make push
